### ISSUE TITLE
Asking for Gerber Files

### ISSUE THREAD

**Issue by yumnadzakiyyah** [PeterJBurke/Nanostat#1]
I am not able to find any Gerber files in the repository. May I got the access to the Gerber File of the Nanostat? Thank you in advanced, it helps me a lot to better understand the work flow of potentiostat!

**Comment by TANG617** [comment]
Hi, did you find the Gerber files? I am still looking for it. Thanks the author again for excellent work.

**Comment by flukesuntisak** [comment]
> I am not able to find any Gerber files in the repository. May I got the access to the Gerber File of the Nanostat? Thank you in advanced, it helps me a lot to better understand the work flow of potentiostat!

Any update on Gerber file? I am unable to find it too.
Thank you

**Comment by TANG617** [comment]
No, but I found an image of schematic attached by the essay. I tried to build my own NanoStat, but I failed because of lots of unpredictable issues. Request for help by the author!

**Comment by PeterJBurke** [comment]
Please check the updated readme. The gerber files have been added. Also there is a Youtube tutorial about how to order the boards.

**Comment by yumnadzakiyyah** [comment]
Well noted, thank you so much for the help! Do really appreciate it!

Best regards,

*Yumna Dzakiyyah*
+6281549593816
***@***.***


Pada tanggal Jum, 26 Agu 2022 pukul 02.22 Peter Burke <
***@***.***> menulis:
