### ISSUE TITLE
Constant potential electrolysis

### ISSUE THREAD

**Issue by c-jw** [PeterJBurke/Nanostat#10]
Dr. Burke,

I have one more question about applications of the Nanostat, then I promise to leave the issues board alone for a while.

Do you think the Nanostat hardware would be capable of constant potential electrolysis?  I haven't found other applications in some googling around of others using the LMP91000 for this process.  

I recognize I would need to do some programming to achieve this.  If I do implement this successfully, I will fork the repo and share everything back.

Thank you for your thoughts!

**Comment by PeterJBurke** [comment]
Yes.
Use the DC tab. It is meant for noise test on the readings. But you can use it to DC bias.
The only question is the max current you would need to check that.
