### ISSUE TITLE
I can not connected to nanostat.

### ISSUE THREAD

**Issue by flukesuntisak** [PeterJBurke/Nanostat#2]
Dear Prof. Burke, @PeterJBurke 

I have already compiled and transferred the firmware to the board. The board shows wifi "nanostatAP".

Now I am stuck on how to control the board using the web . I can not open ip address 192.168.4.1 and nanostat.local either.

Do you have any suggestion?

Regards,
Suntisak

**Comment by PeterJBurke** [comment]
I fixed the readme. 
Basically when in AP mode you have to go to 192.168.4.1 then you get the webpage to enter your wifi SSID and pwd.
Reboot, then you can go to ether nanostat.local when connected to your local network, or the IP address assigned by your local router.

**Comment by flukesuntisak** [comment]
I am already connected to the AP, but I don't know why I am not able to access 192.168.4.1 on both my smartphone and PC.

If not too much, could you please provide me a bit of help?

to make sure I am doing it the correct way.

After downloading the file from GitHub, I can then transfer the firmware by opening this download folder using PlatformIO. 
first clicking the build button to compile it. Then, click the upload button.

Am I doing it correctly?

note: i fabricaates nanostat Version3dot5dot1.

**Comment by PeterJBurke** [comment]
OK. I put a "troubleshooting access point" in the readme. Please use it to confirm you have an IP address on your PC.

It sounds like you uploaded the firmware correctly, but you did not upload the website files (html files). You need to upload all of the html and other files from the "data" directory in the repo. I put a link to some youtube tutorials about how to do this in the readme. From the new readme:

You also need to transfer the website files in the data directory of this repo. This includes all the html files and js (javascript) files that serve up the website. ESP32 has a disk structure called "SPIFFS". For some tutorials on this see: https://www.youtube.com/watch?v=Pxpg9eZLoBI and https://www.youtube.com/watch?v=NVD46mRbVXM

**Comment by flukesuntisak** [comment]
Very appreciate!
I will try to do it as you recommend.

**Comment by flukesuntisak** [comment]
It does work now. Thank you !

However, I obtained the CV signal of Fe(CN)6 as shown below. Do I have to configure something?
![1](https://user-images.githubusercontent.com/111621240/192079099-ddb264db-32bd-40dd-aaed-fafb5dfc3d3f.jpg)

**Comment by flukesuntisak** [comment]
this is IV curve, obtained by connecting to dummy cell
![123](https://user-images.githubusercontent.com/111621240/192092699-d6c27b94-9f48-4590-b8da-43140ed56d43.jpg)

**Comment by PeterJBurke** [comment]
I would recommend to test the nanostat on a resistor to confirm it is working and calibrated correctly. Also make sure to run the calibration routine. Instructions on the "Cal" part.

The resistance value 10 kohm to 100 kohm is probably a good test. It depends on your cell.

What is your dummy cell? If you give details it would help troubleshoot.

Once that is set up, then it is beyond the scope of this github account, but you need to get your electrochemical cell working properly. I don't know the details, if you post them I can help troubleshoot, but it is difficult to remotely troubleshoot the details of the cell.

The peak currents you expect for your experiment depend on the concentration and electrode area. You can look at our paper for the exact values we used, and the model number for the electrodes.

In addition, here is a good reference paper for theory and operation is:

Elgrishi, N., Rountree, K. J., McCarthy, B. D., Rountree, E. S., Eisenhart, T. T., & Dempsey, J. L. (2018). A Practical Beginner’s Guide to Cyclic Voltammetry. Journal of Chemical Education, 95(2), 197–206. https://doi.org/10.1021/acs.jchemed.7b00361

It looks like you might have a dirty working electrode, and possibly your reference electrode is dry. 
We had that problem and then we switched to a gold working electrode (instead of glassy carbon), 
which is much easier to keep clean. 

Also, our Ag/AgCl reference electrode was dry and old, we had to replace it with a new one. Your second plots seem to show some instability/hysteris which may be caused by a faulty reference electrode.

You might also want to contact Basi or whoever your electrode company is. If using your own home made electrodes, try cleaning them.

**Comment by flukesuntisak** [comment]
![image](https://user-images.githubusercontent.com/111621240/192126946-d483a40b-9227-429b-99c2-32fcbd3ccf39.jpg)
This is the dummy cell, i used

**Comment by flukesuntisak** [comment]
For electrochemical experiments, i used a commercial screen-printed electrode. The CV was performed in 5mM Fe(CN)6 containing 0.1M KCl solution.  this is the signals I got. BTW, in setup, i dont know about TIA gain (it was set at 350kohm for this experiment)
![image](https://user-images.githubusercontent.com/111621240/192127433-1b7742e8-dc55-4402-9e88-e0952e28ce74.png)

**Comment by flukesuntisak** [comment]
![Uploading image.jpg…]()

**Comment by flukesuntisak** [comment]
Good news,  it is working !, when I set the TIA to 7 kOhm, 

![image](https://user-images.githubusercontent.com/111621240/192127589-77e594cb-af14-4c51-8e08-e13deea84d00.png)

and this is 3.5 kOhm

![image](https://user-images.githubusercontent.com/111621240/192127654-743fd782-655a-4748-96c7-33583f5e4a6b.png)

Thank you

**Comment by PeterJBurke** [comment]
Great!
If TIA is too large, the ADC saturates.

**Comment by Balakrishna181** [comment]
> Good news, it is working !, when I set the TIA to 7 kOhm,
> 
> ![image](https://user-images.githubusercontent.com/111621240/192127589-77e594cb-af14-4c51-8e08-e13deea84d00.png)
> 
> and this is 3.5 kOhm
> 
> ![image](https://user-images.githubusercontent.com/111621240/192127654-743fd782-655a-4748-96c7-33583f5e4a6b.png)
> 
> Thank you

Previously, as you mentioned in the above graph without calibration, we also got the same as you described. However, we are now encountering difficulties in replicating the results presented in the graphs.

We believe this might be related to the calibration of the nanostat. I am unable to get the results as you got. Could you kindly provide details about the calibration procedure or any specific parameters you followed to achieve the graphs presented after using 7, 3.5 Kohms?
I attached the graphs i got as the result. kindly give the solution to achieve perfect CV,NPV etc.,
Your insights and guidance would be immensely helpful in addressing this issue and ensuring that we are aligning our setup with your methodology.

Thank you in advance for your assistance. We look forward to your response.

![Image](https://github.com/user-attachments/assets/a7ea5e28-daa1-4f01-8d95-6972bef7b8b9)
![Image](https://github.com/user-attachments/assets/71dfa9af-9472-4d7c-9782-673b672c4b5a)
![Image](https://github.com/user-attachments/assets/df068bde-0dcf-4884-b290-102eec096dbc)

**Comment by PeterJBurke** [comment]
Hi-
In general, make sure to calibrate. The instructions to calibrate are on the help page on the nanostat webpage.

You should use a test resistor with approximately the amount of current you expect from your cell, and adjust the gain for it.

It seems CV is working for you correct? But the other modes give no detectable current (less than 0.1 microamp). Is it the same cell that gives CV with 100 microamps? If not, try the same cell.

Also,  can you test your cell with a commercial potentiostat to confirm the cell is working?

**Comment by Balakrishna181** [comment]
> Hi- In general, make sure to calibrate. The instructions to calibrate are on the help page on the nanostat webpage.
> 
> You should use a test resistor with approximately the amount of current you expect from your cell, and adjust the gain for it.
> 
> It seems CV is working for you correct? But the other modes give no detectable current (less than 0.1 microamp). Is it the same cell that gives CV with 100 microamps? If not, try the same cell.
> 
> Also, can you test your cell with a commercial potentiostat to confirm the cell is working?

No, I am not getting the correct CV results and dont know how to achieve it, can you provide any circuitry for the configuration of test resistor and what to do exactly for achieving all these results.(CV,NPV,IV etc.,)

![Image](https://github.com/user-attachments/assets/331d4608-fbfd-47db-8f92-0932e61c224c)

**Comment by Balakrishna181** [comment]
> It does work now. Thank you !
> 
> However, I obtained the CV signal of Fe(CN)6 as shown below. Do I have to configure something? ![1](https://user-images.githubusercontent.com/111621240/192079099-ddb264db-32bd-40dd-aaed-fafb5dfc3d3f.jpg)

sir, How you achieved the results of CV from this. How you configured to get these results 

![Image](https://github.com/user-attachments/assets/0180a3df-27b0-4556-8025-c902552b1343)
