### ISSUE TITLE
This is almost impossibly useful for me!

### ISSUE THREAD

**Issue by RandoSY** [PeterJBurke/Nanostat#3]
Your instructions are faultless on a MAC as well. The serial port auto-detects for uploading, and SPIFFS file uploading from Platform.io/VS Code works as well.

Thanks so much for posting!!!

![Screen Shot 2022-12-27 at 5 52 09 PM](https://user-images.githubusercontent.com/609947/209739357-5ff636f5-da26-43f7-848a-df7472f7e0e2.png)

![Screen Shot 2022-12-27 at 8 02 35 PM](https://user-images.githubusercontent.com/609947/209741699-ed07e923-e4db-43cb-aafb-a6ed34ed662a.png)

**Comment by PeterJBurke** [comment]
Great to hear it! This will be useful for mac users.
