### ISSUE TITLE
detecting cyanide for water contamination

### ISSUE THREAD

**Issue by krasi-georgiev** [PeterJBurke/Nanostat#4]
Do you think this can be used for detecting cyanide and what kind of changes would be required?

**Comment by PeterJBurke** [comment]
The paper demonstrated detection of potassium ferricyanide. Other species should be possible.
The paper was about the electronics, and the electrode and chemistry is another topic. The references in the paper, including the book by Bard, is a good start to look at detection of other chemicals.
But users should be extremely careful with toxic chemicals and follow safety protocols!
