### ISSUE TITLE
Why is  the potentiostat needed with the QCM sensors?

### ISSUE THREAD

**Issue by krasi-georgiev** [PeterJBurke/Nanostat#5]
Will try  to use the device with QCM sensor for detecting carbamate.

Do you know  whether a potentiostat is needed and if yes would appreciate some pointers or references where to read more about this.

**Comment by PeterJBurke** [comment]
QCM needs MHz frequency waveforms, which the NanoStat is not able to produce easily.

You might start here:
https://en.wikipedia.org/wiki/Quartz_crystal_microbalance
