### ISSUE TITLE
Power problem

### ISSUE THREAD

**Issue by MargotSchultz** [PeterJBurke/Nanostat#6]
Hello,

We got the electonic plate and the welds are good, but we got a power problem. 
When we compile the code we get this error message: 
**"Power peak on USB port
Unknown USB device needs more power than what the port can provide."**

Did anyone had the same problem?

![image](https://github.com/PeterJBurke/Nanostat/assets/146357743/06e368ca-ddc5-4162-81e7-3f9d66685970)

**Comment by PeterJBurke** [comment]
That is probably a power supply problem. Try using a different USB power source.
Note, the power from a USB battery bank (such as used for cell phones) usually turns off if the current is low.
In the case of the nanostat, the current is low.

**Comment by PeterJBurke** [comment]
see also issue #9 
issue #9 
https://github.com/PeterJBurke/Nanostat/issues/9
