### ISSUE TITLE
Electrical Impedance Spectroscopy

### ISSUE THREAD

**Issue by c-jw** [PeterJBurke/Nanostat#7]
This is a neat design, with a lot of hard work involved.  Thank you for making and sharing this great piece of low-cost, portable technology.

I see that electrical impedance spectroscopy (EIS) is not built in to the software controls.  Is there a hardware obstacle to achieving EIS with this design?  Other obstacles?  More generally, is this design capable of EIS?

Thank you!

**Comment by PeterJBurke** [comment]
In principle it could be programmed, but you would have to synthesize a sine wave digitally. I don't know how high in frequency this would work.
