### ISSUE TITLE
About Cyclic voltammetry range.

### ISSUE THREAD

**Issue by manhtran98bg** [PeterJBurke/Nanostat#8]
Hello, I am very impressed by what you shared in the NanoStats project. Currently I have a Potentiostat project with the required Cyclic voltammetry range from -1.5V -> 1.5V. Does your project meet this requirement? Hope to hear from you soon! Thanks a lot.

**Comment by PeterJBurke** [comment]
The range is -600 mV to + 600 mV.

The LMP91000 can bias the cell up to 20% of the DAC output of the ESP32. The ESP32 DAC is very non-linear above 3 V, and cannot go above 3.3 V which is the power supply voltage. Therefore the cell voltage is limited to 3 V * 20% = 600 mV, in either direction.
